LobbyServer:
  - 'BedwarsLobby#1'
BungeeMode: 'Game'
arena-start-tutorial:
  - '§a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬'
  - '§f                                §l起床战争'
  - ''
  - '§e§l      保护你的床并破坏敌人的床。通过从资源刷新点获取铁锭，金锭'
  - '§e§l                绿宝石和钻石来升级，使自身和队伍变得更强。'
  - ''
  - '§a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬'
Map:
  Name: "王国"
  Mode: "4v4v4v4"
  ModeType: "4v4v4v4"
  mini: "miniKa3b"
  WorldName: "playworld"
  MaxPlayer: 16
  NeedPlayer: 1
  Size: 200
  Spawn: "-0.5,132,-0.5,0,0"
  Spectator: "0.5,125,0.5,0,90"
  resources:
    iron-1: 1
    gold-1: 4
    iron-2: 0.8
    gold-2: 3
    iron-3: 0.5
    gold-3: 2
    emerald-1: 30
    iron-4: 0.3
    gold-4: 1
    emerald-2: 15
  红队:
    Bed: "66.0,24.0,0.0,67.0,24,0"
    Spawn: "75.5,24,0.5,90,0"
    resources: "79.5,23.5,0.5"
    chest: "74,24,3"
  蓝队:
    Bed: "0,24,-66,0,24,-67"
    Spawn: "0.5,24,-74.5,0,0"
    resources: "79.5,23.5,0.5"
    chest: "3,24,-73"
  绿队:
    Bed: "-66,24,0,-67,24,0"
    Spawn: "-74.5,24,0.5,-90,0"
    resources: "-78.5,23.5,0.5"
    chest: "-73,24,-2"
  黄队:
    Bed: "0,24,66,0,24,67"
    Spawn: "0.5,24,75.5,180,0"
    resources: "0.5,23.5,79.5"
    chest: "-2,24,74"
  generator:
    Diamond:
      - "52.5,19,52.5"
      - "-51.5,19,52.5"
      - "-51.5,19,-51.5"
      - "52.5,19,-51.5"
    Emerald:
      - "3.5,26,-2.5"
      - "-2.5,26,3.5"